version: '3'
services:
    database:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '14306:3306'
        environment:
            MYSQL_DATABASE: todoist-gsheets
            MYSQL_ROOT_PASSWORD: devRootPassword
            MYSQL_USER: gsheets_admin
            MYSQL_PASSWORD: gsheetsAdminPassword
