name: Audit check
on: pull_request

# Only a single workflow will run at a time. Cancel any in-progress run.
concurrency:
    group: audit-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    audit:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.4.0

            - name: Configure doist package repository
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
              with:
                  node-version-file: '.nvmrc'
                  scope: '@doist'

            - name: Bootstrap
              run: npm i

            - name: Run Audit Check
              run: npm run audit --production
