name: Google Sheets CI
on:
    pull_request:
        paths:
            - 'src/**'
            - 'package.json'

# Only a single workflow will run at a time. Cancel any in-progress run.
concurrency:
    group: google-sheets-ci-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    ci-google-sheets:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        services:
            mysql:
                image: mysql:8.0.40-debian
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: e2e-tests
                    MYSQL_USER: gsheets_admin
                    MYSQL_PASSWORD: gsheetsAdminPassword
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        env:
            TEST_DB_HOST: 127.0.0.1
            TEST_DB_PORT: 3306
            TEST_DB_USERNAME: gsheets_admin
            TEST_DB_PASSWORD: gsheetsAdminPassword
            TEST_DB_NAME: e2e-tests

        steps:
            - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.4.0

            - name: Configure doist package repository
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
              with:
                  node-version-file: '.nvmrc'
                  scope: '@doist'

            - name: Bootstrap
              run: npm ci

            - name: Fix MySQL auth plugin for gsheets_admin user
              run: |
                  docker exec $(docker ps -q -f ancestor=mysql:8.0.40-debian) \
                    mysql -uroot -proot -e \
                    "ALTER USER 'gsheets_admin'@'%' IDENTIFIED WITH mysql_native_password BY 'gsheetsAdminPassword'; FLUSH PRIVILEGES;"

            - name: Run CI Check
              run: npm run integrity-check
