name: Google Sheets CI
on:
    pull_request:
        paths:
            - 'src/**'
            - 'package.json'

# Only a single workflow will run at a time. Cancel any in-progress run.
concurrency:
    group: google-sheets-ci-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    ci-google-sheets:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.4.0

            - name: Configure doist package repository
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
              with:
                  node-version-file: '.nvmrc'
                  scope: '@doist'

            - name: Bootstrap
              run: npm ci

            - name: Run CI Check
              run: npm run integrity-check
